GET http://localhost:3000/games/

###

GET http://localhost:3000/games/6547cc7b47e93b67387b0ad2

###

POST http://localhost:3000/games
Content-Type: application/json

{
    "name": "Overwatch"
}

###

DELETE http://localhost:3000/games/654a206f72e2cceac89d2bd5


###

PATCH http://localhost:3000/games/6547ce29217284ac3cffa6fd
Content-Type: application/json

{
    "name": "Fortnite"
}

