GET http://localhost:3000/players/

###

GET http://localhost:3000/players/6547c6bc752b891b9f72c53e

###

POST http://localhost:3000/players
Content-Type: application/json

{
    "name": "Jack"
}

###

DELETE http://localhost:3000/players/6547c4de0846c3f0a26f0c04


###

PATCH http://localhost:3000/players/6547c6bc752b891b9f72c53e
Content-Type: application/json

{
    "name": "Ethan"
}

